name: "Nuget"

on:
  workflow_call:
    inputs:
      name:
        required: false
        type: string
      push:
        default: false
        required: false
        type: boolean
      version:
        required: false
        type: string
        default: v0.0.0-ci
      host:
        required: false
        type: string
    secrets:
      token:
        required: false
      nuget:
        required: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set VERSION variable from tag
        run: |
          TAG=${{ inputs.version }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION}
      - name: Test
        run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
      - name: Pack
        if: inputs.push
        run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
      - name: Push
        if: inputs.push
        run: dotnet nuget push ${{inputs.name}}.${VERSION}.nupkg -k ${{secrets.nuget}} -s ${{ inputs.host }}
