name: "On PR"

on:
  pull_request:
    branches:
      - master
      - development

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
  build:
    uses: .github/workflows/nuget.yml
