name: "On Push/Merge"

on:
  push:
    branches:
      - master
      - development

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
  build:
    uses: tagshelfsrl/github-actions/.github/workflows/nuget.yml@v1.13.1

  release:
    needs: [build]
    uses: tagshelfsrl/github-actions/.github/workflows/semver.yml@v1.13.1
    secrets:
      token: ${{secrets.PAT_TOKEN}}

