name: "On PR"

on:
  pull_request:
    branches:
      - master
      - development

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
  build:
    uses: tagshelfsrl/github-actions/.github/workflows/nuget.yml@v1.13.1
