name: "On Push/Merge"

on:
  push:
    branches:
      - master
      - development

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/nuget.yml
    with:
      version: ${{github.ref_name}}

  release:
    needs: [build]
    uses: ./.github/workflows/semver.yml
    secrets:
      token: ${{secrets.PAT_TOKEN}}

