name: "On Tag Pushed"

on:
  push:
    tags:
      - v*

jobs:
  build:
    uses: ./.github/workflows/nuget.yml
    secrets: 
      nuget: ${{secrets.NUGET_TOKEN}}
    with:
      name: TagShelf.Alfred.ApiWrapper
      host: https://api.nuget.org/v3/index.json
      push: true
      version: ${{github.ref_name}}
