name: "SemVer"

on:
  workflow_call:
    inputs:
      nodeVersion:
        type: string
        default: 20
    secrets:
      token:
        required: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/github @semantic-release/git @semantic-release/changelog
      - name: Release
        run: npx semantic-release
        env:
          CI: true
          GH_TOKEN: ${{ secrets.token == '' && secrets.GITHUB_TOKEN || secrets.token }}
          GITHUB_TOKEN: ${{ secrets.token == '' && secrets.GITHUB_TOKEN || secrets.token }}
